import type { DocPRPreview, DriftResult } from '../types';

function buildDiff(docPath: string, original: string, revised: string): { diff: string; additions: number; deletions: number } {
  const origLines = original.split('\n');
  const newLines = revised.split('\n');
  const diff: string[] = [`--- a/${docPath}`, `+++ b/${docPath}`];
  let additions = 0;
  let deletions = 0;

  const max = Math.max(origLines.length, newLines.length);
  for (let i = 0; i < max; i++) {
    const o = origLines[i];
    const n = newLines[i];
    if (o === n) {
      if (o !== undefined) diff.push(` ${o}`);
    } else {
      if (o !== undefined) {
        diff.push(`-${o}`);
        deletions++;
      }
      if (n !== undefined) {
        diff.push(`+${n}`);
        additions++;
      }
    }
  }

  return { diff: diff.join('\n'), additions, deletions };
}

/** Use API preview, or synthesize one locally for legacy github pr_url responses. */
export function resolvePrPreview(result: DriftResult, repo = 'acme/sample-app'): DocPRPreview | null {
  if (result.pr_preview) return result.pr_preview;
  if (!result.suggested_rewrite) return null;

  const { diff, additions, deletions } = buildDiff(
    result.doc_path,
    result.original_content,
    result.suggested_rewrite,
  );
  const prNumber = result.pr_url?.match(/\/pull\/(\d+)/)?.[1] ?? '—';

  return {
    pr_number: typeof prNumber === 'string' && prNumber !== '—' ? Number(prNumber) : 0,
    repo,
    title: `docs: fix drift — ${result.section_heading.replace(/^#+\s*/, '')}`,
    body: `Auto-generated by DocAnchor (local preview).\n\n### Section\n${result.section_heading}\n\nDoc path: \`${result.doc_path}\``,
    base_branch: 'main',
    head_branch: 'docanchor/fix-preview',
    status: 'open',
    author: 'docanchor-bot[bot]',
    doc_path: result.doc_path,
    section_heading: result.section_heading,
    diff,
    additions,
    deletions,
  };
}
